### PR TITLE
fix: correct module import path for maxmind/actix-web-v4

### PR DESCRIPTION
**Pull request by ethowitz**
There was a compile error that wasn't caught by CI. As of right now, I think CI only checks compilation with each feature individually but not combinations of features, and this particular error only occurs when compiling with _both_ the `maxmind` and `actix-web-v4` features.

### CODE REVIEW

**Comment by ethowitz** [comment]
We may want to use [`--feature-powerset`](https://github.com/taiki-e/cargo-hack#--feature-powerset) instead of `--each-feature` with `cargo hack`, though I guess it would fail when compiling `actix-web-v3` with `actix-web-v4`...

**Comment by jrconlin** [comment]
Wait, I'm confused by that warning.
It's saying that one of the crates will be discarded, but not which one.

**Comment by ethowitz** [comment]
I think it's saying that the entire `actix-web-location` crate will be discarded if the crate is compiled with both `actix-web-v3` and `actix-web-v4`, but I could be wrong. My point above was just that compilation does, in fact, succeed (albeit, with a warning) when including both features, which is sufficient for CI purposes

**Comment by jrconlin** [comment]
Yeah, I'm just concerned about whatever decides to include this crate might have "unexpected behaviors" (Honestly, I'd hold off updating this crate 'til January for kind of that reason). 

Remind me to tell you my "Well, it compiled" story sometime. It's a delightfully itchy scar.

**Comment by mythmon** [comment]
The warning above was generated by this code:

```rust
#[cfg(any(
    all(feature = "actix-web-v3", not(feature = "actix-web-v4")),
    all(not(feature = "actix-web-v3"), feature = "actix-web-v4")
))]
```

Every export at the top level of the location crate has this attached:

```rust
#[cfg(any(
    all(feature = "actix-web-v3", not(feature = "actix-web-v4")),
    all(not(feature = "actix-web-v3"), feature = "actix-web-v4")
))]
```

If both features are enabled it always prints that deprecation warning (which is the only compile-time-warning I know how to print), and removes all the exports. Any code that actually tries to use this crate will fail because of that, but it lets us pass our CI.

@ethowitz For some reason I though that the feature powerset would fail, but maybe that was from before I implemented that feature interlock above? I'm not sure. Since it seems to works, like you demonstrated, I agree that it's a good idea to use.

**Review by mythmon — CHANGES_REQUESTED** [review]
This is a problem that CI should have caught. Lets update CI in such a way that it would catch this (with feature powerset) as a part of the change.

**Review by mythmon — APPROVED** [review]

**Pull request merged**
